# Generated by Django 4.2.5 on 2024-01-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_kpi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='products_retained',
            new_name='products_returned',
        ),
    ]
